### PR TITLE
:construction: Working prototype

### PR DESCRIPTION
**Pull request by The-Wary-One**
We can now play with the Seed, Land, Fruit and Fertilizer contracts from the front app. We still have a lot to work on but it should be enough to start developing the UI without mocking everything ! :grin:

### CODE REVIEW

**Review by tomosaigon — COMMENTED** [review]
French InsuffisantFunds -> English InsufficientFundst

**Review by tomosaigon — APPROVED** [review]
In my head, I imagined dehydrateRate to be an hourly rate. It can be seconds but then it becomes a very small number. We need to make sure the scale is correct and divide by hours (3600) if using hourly rates.

Using 256 bits for a number from 0 to 100 might be too much hehe. Also why we can use an hourly rate as we do not need the number to be granular.

Comment "Check if the token exists and if the sender owns the seed AND the land" - it seems to only check ownership but not separately token existence.

Why don't we allow a 3rd person to water() my own tree? Like a good neighbor.

I'm not sure if watering a dead tree is invalid. It shouldn't revive or make the tree grow but it can be tried. It can update lastWatered but then make sure we don't change state from DEAD.

Why can't we move() a TreeState.SEED ? Just a DEAD tree needs to be burn()'d. But maybe that should also be allowed - moving a dead tree from your land to another land you own. We might want to add a fee to move() then (TODO later).

**Review by tomosaigon — APPROVED** [review]
Comment: // Mapping from a blockHash to the number of minted seeds in this block

It's actually mapping block number not hash.

This is defined: uint8 constant dnaBits = 32;
but later you hard-code "32" literal: bytes4 dna = bytes4(hash << mintedTokensPerBlock[block.number] * 32);

**Review by tomosaigon — APPROVED** [review]
OK (looks like rates are normalized to hours here so ignore earlier comments)

**Review by tomosaigon — APPROVED** [review]
Good!

**Comment by The-Wary-One** [comment]
> Using 256 bits for a number from 0 to 100 might be too much hehe. Also why we can use an hourly rate as we do not need the number to be granular.

I agree. Where do you see this ? It would have been even better if you commented on the lines directly :grin: .

> Comment "Check if the token exists and if the sender owns the seed AND the land" - it seems to only check ownership but not separately token existence.

The trick here is that the `ERC721-ownerOf` function does check the existence of the token :stuck_out_tongue_winking_eye: 
```solidity
function ownerOf(uint256 tokenId) public view virtual override returns (address) {
        address owner = _owners[tokenId];
        require(owner != address(0), "ERC721: owner query for nonexistent token");
        return owner;
}
```
So i think this code and comment are correct
```solidity
// Check if the token exists and if the sender owns the seed
if (ownerOf(_seedId) != msg.sender) revert UnauthorizedError()
```

> Why don't we allow a 3rd person to water() my own tree? Like a good neighbor.

We could now yes, it is a relic from a design where you could kill your tree by watering it to much lol

> I'm not sure if watering a dead tree is invalid. It shouldn't revive or make the tree grow but it can be tried. It can update lastWatered but then make sure we don't change state from DEAD.

I'm against this for now because it means we would need to store the calculated tree state. Today it is just derived from the water level.
```solidity
// Check if the tree is dead
int256 _waterLevel = waterLevel(_seedId);
if (_waterLevel <= driedDeath) return TreeState.DEAD;
```
Its added complexity for something that changes nothing in the game isn't worth it and we already protect the player from wasting fertilizer on a non adult tree. :smile: 

> Why can't we move() a TreeState.SEED ? Just a DEAD tree needs to be burn()'d. But maybe that should also be allowed - moving a dead tree from your land to another land you own. We might want to add a fee to move() then (TODO later).

It is also a relic hehe. I thought before that TreeState.SEED meant "not planted" but now it can be a seed and be planted. So we just need to check if it is planted instead.

> Comment: // Mapping from a blockHash to the number of minted seeds in this block
> 
> It's actually mapping block number not hash.

Did you review the latest commit ? The closest comment i can find now is about `mintedTokensPerBlock` but it was already corrected.
```solidity
// Mapping from a block number to the number of minted seeds in this block
mapping (uint256 => uint8) mintedTokensPerBlock;
```

**Review by tomosaigon — APPROVED** [review]
Looks good

**Pull request merged**
